### ISSUE TITLE
__pod.tpl invalid indentation

### ISSUE THREAD

**Issue by martinlillemets** [avakarev/gatus-chart#46]
It seems that the version 2.5.5 contains invalid __pod.tpl.

The indentation value for go-template functions is incorrect for the following lines in __pod.tpl
- Line 14: `{{- toYaml .Values.podSecurityContext | nindent 8 }} `// This should be indented as 2
- Line 18: `{{- toYaml .Values.securityContext | nindent 12 }} `// This should be indented as 6
- Line 94: `{{ toYaml . | indent 8 }}` // This should be indented as 2

Faulty yaml can be easily reproduced using the following:
```shell
helm pull gatus/gatus --version 2.5.5
tar -xf gatus-2.5.5.tgz
helm template gatus --set 'nodeSelector.type=monitoring'
```
Helm version used:
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Faulty generated Deployment:
```yaml
# Source: gatus/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-gatus
  namespace: default
  labels:
    helm.sh/chart: gatus-2.5.5
    app.kubernetes.io/name: gatus
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v4.3.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gatus
      app.kubernetes.io/instance: release-name
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gatus
        app.kubernetes.io/instance: release-name
      annotations:
        checksum/config: 1846342a475c8692458ea95c9923286d41772fd2c01f7f969d1de05c963bf980
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: false
      securityContext:
              fsGroup: 65534
      containers:
        - name: gatus
          securityContext:
                  readOnlyRootFilesystem: true
                  runAsGroup: 65534
                  runAsNonRoot: true
                  runAsUser: 65534
          image: "twinproduction/gatus:v4.3.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: release-name-gatus
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {}
          volumeMounts:
            - name: release-name-gatus-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: release-name-gatus-config
          configMap:
            name: release-name-gatus
      nodeSelector:
              type: monitoring
```
